apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmate-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmate-server
  template:
    metadata:
      labels:
        app: tmate-server
    spec:
      containers:
      - image: ghcr.io/scality/tmate-ssh-server/tmate-ssh-server:latest
        name: tmate-server
        ports:
          - name: daemon-port
            containerPort: 2200
          - name: client-port
            containerPort: 2201
        env:
          - name: "SSH_PORT_LISTEN_DAEMON"
            value: "2200"
          - name: "SSH_PORT_LISTEN_CLIENT"
            value: "2201"
          - name: "USE_PROXY_PROTOCOLPROTOCOL"
            value: "0"
