---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "tmate-server.fullname" . }}
  labels:
    {{- include "tmate-server.labels" . | nindent 4 }}
type: Opaque
data:
  tmate-server-rsa-key: {{ .Values.tmateServerRsaKey | b64enc }}
  tmate-server-ed25519-key: {{ .Values.tmateServerEd25519Key | b64enc }}
