apiVersion: v1
kind: Service
metadata:
  name: tmate-server-lb-client
spec:
# https://cloud.google.com/kubernetes-engine/docs/concepts/service-load-balancer-parameters#fw_ip_address
  {{- with .Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
  - name: client-port
    protocol: TCP
    port: {{ .Values.clientPort }} # Port on the service
    targetPort: {{ .Values.clientPort }} # Port on the pod
  selector:
    # Labels that match the targgeting pods
    app: {{ include "tmate-server.name" . }}
  sessionAffinity: None
  type: LoadBalancer
