name: action
on:
  push:
    branches: ['**']
  workflow_dispatch: {}
jobs:
  docker-build:
    uses: scality/workflows/.github/workflows/docker-build.yaml@v1
    with:
      name: tmate-ssh-server
      namespace: scality
      push: true
      tag: latest
